### ISSUE TITLE
Referring to your repo from mine?

### ISSUE THREAD

**Issue by jerabaul29** [npuljc/RL_control_Nek5000#1]
Hi @npuljc et al :) 

I just read your JFM RG Preprint, congratulations on a beautiful manuscript, hope it gets published soon :) .

It is very nice that you coupled the DRL framework with Nek5000, this opens the way for many exciting studies. Would you be ok if I mention your repository from my repository at https://github.com/jerabaul29/Cylinder2DFlowControlDRL ? I was thinking about adding a small subsection after the "Update, training in parallel" subsection at the start of the readme, something like:

"
# Update: coupling with spectral CFD code released by another research group

The DRL control can be coupled with a variety of CFD codes, and this was recently released by *Li and Zhang*, **Reinforcement-learning-based control of confined cylinder wakes with stability analyses**, in the case of Nek5000. Their code is available at: https://github.com/npuljc/RL_control_Nek5000 .
"

I think that would be useful to people browsing for code, looking for inspiration etc, as your code shows very nicely how DRL could be coupled to some more involved CFD codes, and creating a "web of knowledge" here on github by linking important resources may be very helpful to the reader.

Of course if you have any issues with me putting a link to your repo just let me know and I will not do it, no reasons asked :) .

**Comment by npuljc** [comment]
Hi Dr. Rabault,

I'm so glad to hear from you! Of course, please add the link and I'm grateful for that!
Also, I would like to acknowledge your contribution. Without that, we cannot make our work done. Thank you so much!

Best,
Jichao

**Comment by jerabaul29** [comment]
Added here, let me know if you have any comments :) : https://github.com/jerabaul29/Cylinder2DFlowControlDRL/commit/c15ef535f37f067d34184f76986845a96ccd7c61 .

It is a real pleasure to see that different groups start building on each others works and benefit from open source release of DRL-CFD codes, really happy and grateful to hear that you found our code release useful :) . Thanks for sharing your code :) .
